name: News Bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - run: node index.js
        env:
          SUPABASE_URL: ${{ https://afrwjstlffvsueqjtjyd.supabase.co }}
          SUPABASE_ANON_KEY: ${{ sb_publishable__oS9ZaaFhADPdUeItOQ-qg_UEZT-GMh }}
          GEMINI_API_KEY: ${{ AQ.Ab8RN6I58G56QKGyUQu4uNZTUgoa4C0bvekOQDIzTZCISYKgnQ }}
